server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081

logging:
  level: DEBUG

graph:
  graphName: test
  graphsonPath: test.graphson

datasource:
  - type: Postgresql
    connectionUrl:
    username:
    password: